name: pull request
on:
  pull_request:
    branches: [ main ]

jobs:
  print-merge-commit:
    runs-on: ubuntu-latest
    steps:
    - name: print merge commit
      run: echo ${{ github.event.pull_request.merge_commit_sha }}

    - name: print head sha
      run: echo ${{ github.event.pull_request.head.sha }}